version: '3.8'

services:
  form-service:
    image: ahilwers/form-service:0.10
    container_name: form-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    depends_on:
      - mongo
    networks:
      - form-network

  mongo:
    image: mongo:6.0
    container_name: form-mongo
    restart: unless-stopped
    volumes:
      - form-data:/data/db
    networks:
      - form-network


networks:
  form-network:
    driver: bridge

volumes:
  form-data:
    driver: local
