# Default configuration for the Form Service

# Allowed origins for CORS
allowed_origins:
  - "http://localhost:8000"  # For local development

# Maximum length for text fields (optional, default: 1000)
# max_field_length: 1000

# MongoDB connection URI (optional, default: mongodb://localhost:27017)
mongo_uri: "mongodb://localhost:27017"

# Basic Auth configuration
# auth:
#   username: "admin"
#   password: "secret"
